import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
const iranSans = localFont({
  src: [
    {
      path: "./fonts/IRANSansXFaNum-Black.ttf",
      weight: "200",
    },
    {
      path: "./fonts/IRANSansXFaNum-Bold.ttf",
      weight: "200",
    },
  ],
  variable: "--font-iran-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        dir="rtl"
        className={`${iranSans.variable}  antialiased flex flex-col h-screen overflow-hidden bg-slate-100`}
      >
        <Header />
        <div className="border border-sky-800 w-full h-full ">{children}</div>
        <h1>footer</h1>
      </body>
    </html>
  );
}
